### ISSUE TITLE
DOOO ITTT!!!!

### ISSUE THREAD

**Issue by DavidLozzi** [jcardente/adventOfCode2021#1]
Happy to see you on here! What tech will you be doing? I'd like to link to your repo from mine, is that okay?

**Comment by jcardente** [comment]
Totally fine to link repos! 

Using Python this year. I was originally hoping to experiment with a new/different language. Perhaps, Scala, Clojure, or Racket. But, I didn't get my act together in time to get prepared (eg. setting up a dev environment, review basic syntax/libraries, etc). 

What are you using?

**Comment by DavidLozzi** [comment]
I'm sticking with ReactJS this year, going to make a UI for it all, cause why not. ;)
